language: python
python:
  # - "3.5"
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install --yes wkhtmltopdf xvfb
  - su -c "printf '#!/bin/bash\nxvfb-run -a --server-args=\"-screen 0, 1024x768x24\" /usr/bin/wkhtmltopdf -q $*' > /usr/bin/wkhtmltopdf.sh"
  - su -c "chmod a+x /usr/bin/wkhtmltopdf.sh"
  - ln -s /usr/bin/wkhtmltopdf.sh /usr/local/bin/wkhtmltopdf
  - pip install pycodestyle codecov
  - pip3 install -r requirements.txt
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - pytest
  - coverage run --branch --source=. -m unittest discover -bv
  - coverage report -m
after_success:
  - codecov
